// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createMockClient() {
  const mockAuth = {
    getSession: async () => ({ data: { session: null }, error: null }),
    onAuthStateChange: () => ({
      data: { subscription: { unsubscribe: () => {} } },
    }),
    signInWithPassword: async (creds: { email?: string }) => ({
      data: { user: { id: "mock-user-id", email: creds.email }, session: null },
      error: null,
    }),
    signUp: async (creds: { email?: string }) => ({
      data: { user: { id: "mock-user-id", email: creds.email }, session: null },
      error: null,
    }),
    signOut: async () => ({ error: null }),
    getUser: async () => ({ data: { user: null }, error: null }),
    getClaims: async () => ({
      data: { claims: { sub: "mock-user-id" } },
      error: null,
    }),
    oauth: {
      getAuthorizationDetails: async () => ({ data: null, error: null }),
      approveAuthorization: async () => ({ data: null, error: null }),
      denyAuthorization: async () => ({ data: null, error: null }),
    },
  };

  const createQueryChain = (data: unknown[] = []): unknown => ({
    select: () => createQueryChain(data),
    insert: (rows: unknown) => createQueryChain(Array.isArray(rows) ? rows : [rows]),
    update: () => createQueryChain(data),
    delete: () => createQueryChain(data),
    eq: () => createQueryChain(data),
    neq: () => createQueryChain(data),
    ilike: () => createQueryChain(data),
    order: () => createQueryChain(data),
    limit: () => createQueryChain(data),
    maybeSingle: async () => ({ data: data[0] ?? null, error: null }),
    single: async () => ({ data: data[0] ?? null, error: null }),
    then: (resolve: (val: unknown) => unknown) =>
      Promise.resolve({ data, error: null }).then(resolve),
  });

  return {
    auth: mockAuth,
    from: () => createQueryChain([]),
  } as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn("[AI Studio] Supabase environment variables not set — using mock client");
    return createMockClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
